export default {
  "get_buyCryptoInfo": '/crypto/buy',
  "post_sendEmail": '/mail/sending',
  "post_login": '/user/login',
  "get_network": '/crypto/network',
  "get_inquiryFee": '/crypto/fee',
  "post_coinSupportedWallet": '/crypto/wallet/check',
  "post_buy": '/trade/create',
  "post_indonesiaBuy": '/pay/idr/submit',
  "post_internationalCard": '/pay/card/submit',
  "get_transactionHistory": '/trade/list',
  "get_payResult": '/pay/result/check',
  "post_outLogin": '/login/to-logout',
  "post_basisIdAuth": '/kyc/auth/check',
  "post_storageBasisIdAuth": '/kyc/auth/create',
  "get_isbasisIdAuth": '/kyc/auth/status',
}
